"""empty message

Revision ID: cb071f943d45
Revises: ff7d4dbf7acf
Create Date: 2026-03-24 16:30:20.637309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb071f943d45'
down_revision = 'ff7d4dbf7acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PERSONAJE', 'VEHICULO', 'LUGAR', 'CRIATURA', 'DROIDE', 'ORGANIZACION', 'ESPECIE', name='tiporecurso'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    # ### end Alembic commands ###
