"""empty message

Revision ID: ff7d4dbf7acf
Revises: ac3c8e1558ab
Create Date: 2026-03-24 16:06:31.650755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff7d4dbf7acf'
down_revision = 'ac3c8e1558ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recurso_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('PERSONAJE', 'VEHICULO', 'LUGAR', 'CRIATURA', 'DROIDE', 'ORGANIZACION', 'ESPECIE', name='tiporecurso'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorito_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_pkey')
    )
    # ### end Alembic commands ###
